# Pandas: Python Library
-  Essential for Data Science
- Preparing Data (Automating Data Preprocessing)
- Get your data in order
- Even more versatile than Excel or Google Sheets
- 2 main datatypes: Series and Dataframes

In [ ]:
# import the libraries
import pandas as pd
import numpy as np

## [Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html)
- column of data (collection of observations about a single variable)
- similar to list
- one dimensional array

In [ ]:
age = pd.Series([11, 22, 31, 24, 25, 66], name='Ages')
age

0    11
1    22
2    31
3    24
4    25
5    66
Name: Ages, dtype: int64

In [ ]:
# relabel the index
age = pd.Series([31, 31, 11, 24, 25, 66], index = ['Nicole', 'Nadine', 'Martin', 'Gerhard', 'Wenge', 'Grandma'], name='Ages')
age

Nicole     31
Nadine     31
Martin     11
Gerhard    24
Wenge      25
Grandma    66
Name: Ages, dtype: int64

In [ ]:
# with a re-labeled index, it can be treated like a dictionary! 
age['Nicole']

31

In [ ]:
# Change the values 
age['Grandma'] = 68
age

Nicole     31
Nadine     31
Martin     11
Gerhard    24
Wenge      25
Grandma    68
Name: Ages, dtype: int64

In [ ]:
# max age
print("Max:", age.max())
print("Index of person with max age: ", age.argmax())
print("Number of unique ages: ", age.nunique())
print("Unique ages: ", age.unique())

Max: 68
Index of person with max age:  5
Number of unique ages:  5
Unique ages:  [31 11 24 25 68]

In [ ]:
age.describe()

count     6.000000
mean     31.666667
std      19.242314
min      11.000000
25%      24.250000
50%      28.000000
75%      31.000000
max      68.000000
Name: Ages, dtype: float64

## [Dataframes](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)
- Dataframe is several columns, one for each variable
- rows and columns
- Group mini-project: University Diversity

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [ ]:
# Checkpoint 1: Copy the the .csv file into your notebook to access the data
df = pd.read_csv( "/content/drive/Shared drives/Data Science for Social Good/Week_1/Day_7/University_Diversity_2019.csv")

In [ ]:
# .head() returns the first 5 rows 
df.head()

  Unnamed: 0     Men  ...  Race and/or ethnicity unknown  Total
0      Brown  3263.0  ...                          316.0   6834
1   Columbia  4548.0  ...                          290.0   9001
2    Cornell  6939.0  ...                         1206.0  14976
3  Dartmouth  2217.0  ...                           62.0   4365
4    Harvard  3389.0  ...                           91.0   6695

[5 rows x 13 columns]

A. Level 1 Task: How would you view rows 2-4 of this dataframe? Think back to splicing from strings, lists, numpy arrays

In [ ]:
# splicing: view rows 2-4
df[2:5]

NameError: ignored

In [ ]:
# Select 1 column
df['Hispanic/Latino']

0         759.00
1        1201.00
2        2079.00
3         459.00
4         735.00
5         556.00
6        1014.00
7         860.00
8    60724311.76
Name: Hispanic/Latino, dtype: float64

In [ ]:
# Select 2 columns by inserting a list of columns
df[['Hispanic/Latino','Black or African American, non-Hispanic']]

   Hispanic/Latino  Black or African American, non-Hispanic
0           759.00                                   463.00
1          1201.00                                   587.00
2          2079.00                                   999.00
3           459.00                                   254.00
4           735.00                                   597.00
5           556.00                                   419.00
6          1014.00                                   770.00
7           860.00                                   463.00
8      60724311.76                              43984096.08

In [ ]:
# view all the column names
df.columns

Index(['Unnamed: 0', 'Men', 'Women', 'Nonresident Aliens', 'Hispanic/Latino',
       'Black or African American, non-Hispanic', 'White, non-Hispanic',
       'American Indian or Alaska Native, non-Hispanic', 'Asian, non-Hispanic',
       'Native Hawaiian or other Pacific Islander, non-Hispanic',
       'Two or more races, non-Hispanic', 'Race and/or ethnicity unknown',
       'Total'],
      dtype='object')

[Set index this dataframe](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.set_index.html#pandas.DataFrame.set_index)

In [ ]:
df.set_index(df['Unnamed: 0'], inplace=True)

In [ ]:
df.head()

           Unnamed: 0     Men  ...  Race and/or ethnicity unknown  Total
Unnamed: 0                     ...
Brown           Brown  3263.0  ...                          316.0   6834
Columbia     Columbia  4548.0  ...                          290.0   9001
Cornell       Cornell  6939.0  ...                         1206.0  14976
Dartmouth   Dartmouth  2217.0  ...                           62.0   4365
Harvard       Harvard  3389.0  ...                           91.0   6695

[5 rows x 13 columns]

In [ ]:
df.index

Index(['Brown', 'Columbia', 'Cornell', 'Dartmouth', 'Harvard', 'Princeton',
       'Penn', 'Yale', 'USA'],
      dtype='object', name='Unnamed: 0')

In [ ]:
df.index[2:5]

Index(['Cornell', 'Dartmouth', 'Harvard'], dtype='object', name='Unnamed: 0')

[Drop a column](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)

In [ ]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [ ]:
df.head()

      Men   Women  ...  Race and/or ethnicity unknown  Total
0  3263.0  3571.0  ...                          316.0   6834
1  4548.0  4453.0  ...                          290.0   9001
2  6939.0  8104.0  ...                         1206.0  14976
3  2217.0  2148.0  ...                           62.0   4365
4  3389.0  3306.0  ...                           91.0   6695

[5 rows x 12 columns]

## Select particular rows and columns: iloc, loc
![alt text](https://shanelynnwebsite-mid9n9g1q9y8tt.netdna-ssl.com/wp-content/uploads/2016/10/Pandas-selections-and-indexing-768x549.png)

In [ ]:
# Known method: splicing
df[2:5]

               Men   Women  ...  Race and/or ethnicity unknown  Total
Unnamed: 0                  ...
Cornell     6939.0  8104.0  ...                         1206.0  14976
Dartmouth   2217.0  2148.0  ...                           62.0   4365
Harvard     3389.0  3306.0  ...                           91.0   6695

[3 rows x 12 columns]

[iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html): check links for examples
- use: indexing
- primarily integer index position based
- [rows, columns]

In [ ]:
df.columns[0:2]

Index(['Men', 'Women'], dtype='object')

In [ ]:
# iloc: isolate the first 5 universities: men, womens
df.iloc[0:5, 0:2]

               Men   Women
Unnamed: 0
Brown       3263.0  3571.0
Columbia    4548.0  4453.0
Cornell     6939.0  8104.0
Dartmouth   2217.0  2148.0
Harvard     3389.0  3306.0

Level 3 Task: Isolate the first 5 universities and all the race-based data

In [ ]:
df.iloc[0:5, 3:11]

            Hispanic/Latino  ...  Race and/or ethnicity unknown
Unnamed: 0                   ...
Brown                 759.0  ...                          316.0
Columbia             1201.0  ...                          290.0
Cornell              2079.0  ...                         1206.0
Dartmouth             459.0  ...                           62.0
Harvard               735.0  ...                           91.0

[5 rows x 8 columns]

In [ ]:
# all rows, men and women columns 
df.iloc[:, 0:2]

                    Men        Women
Unnamed: 0
Brown            3263.0       3571.0
Columbia         4548.0       4453.0
Cornell          6939.0       8104.0
Dartmouth        2217.0       2148.0
Harvard          3389.0       3306.0
Princeton        2670.0       2638.0
Penn             4770.0       5249.0
Yale             2995.0       3094.0
USA         161493845.3  166745677.7

[loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html)
- label based method of splicing 
- df.loc['c', 'b']
- rows, cols

example 1: isolate the first 5 universities and all the race-based data

In [ ]:
df.index[0:5]

Index(['Brown', 'Columbia', 'Cornell', 'Dartmouth', 'Harvard'], dtype='object', name='Unnamed: 0')

In [ ]:
df.columns[2:-1]

Index(['Nonresident Aliens', 'Hispanic/Latino',
       'Black or African American, non-Hispanic', 'White, non-Hispanic',
       'American Indian or Alaska Native, non-Hispanic', 'Asian, non-Hispanic',
       'Native Hawaiian or other Pacific Islander, non-Hispanic',
       'Two or more races, non-Hispanic', 'Race and/or ethnicity unknown'],
      dtype='object')

In [ ]:
df.loc[['Brown', 'Harvard', 'Princeton'], df.columns[2:-1]]

            Nonresident Aliens  ...  Race and/or ethnicity unknown
Unnamed: 0                      ...
Brown                    782.0  ...                          316.0
Harvard                  814.0  ...                           91.0
Princeton                638.0  ...                           70.0

[3 rows x 9 columns]

In [ ]:
df.columns

Index(['Men', 'Women', 'Nonresident Aliens', 'Hispanic/Latino',
       'Black or African American, non-Hispanic', 'White, non-Hispanic',
       'American Indian or Alaska Native, non-Hispanic', 'Asian, non-Hispanic',
       'Native Hawaiian or other Pacific Islander, non-Hispanic',
       'Two or more races, non-Hispanic', 'Race and/or ethnicity unknown',
       'Total'],
      dtype='object')

In [ ]:
df.loc[['Princeton', 'Penn'], df.columns[0:2]]

               Men   Women
Unnamed: 0
Princeton   2670.0  2638.0
Penn        4770.0  5249.0

Level 3 Task: Use loc to isolate the gender data for Princeton, Yale, and Harvard

In [ ]:
df.columns[0:2]

Index(['Men', 'Women'], dtype='object')

In [ ]:
df.loc[['Princeton', 'Yale', 'Harvard'], ['Men', 'Women']]

               Men   Women
Unnamed: 0
Princeton   2670.0  2638.0
Yale        2995.0  3094.0
Harvard     3389.0  3306.0

Use pandas to calculate the percent of students that are men, women, black, white, hispanic, etc

In [ ]:
df.columns

Index(['Men', 'Women', 'Nonresident Aliens', 'Hispanic/Latino',
       'Black or African American, non-Hispanic', 'White, non-Hispanic',
       'American Indian or Alaska Native, non-Hispanic', 'Asian, non-Hispanic',
       'Native Hawaiian or other Pacific Islander, non-Hispanic',
       'Two or more races, non-Hispanic', 'Race and/or ethnicity unknown',
       'Total'],
      dtype='object')

In [ ]:
df.columns[0]

'Men'

In [ ]:
print("Percent_" + df.columns[0])

Percent_Men

In [ ]:
df["Percent_" + df.columns[0]] = df[df.columns[0]]/df['Total']

In [ ]:
df['Percent_Men'] = df[df.columns[0]]/df['Total']

In [ ]:
df["Percent_" + df.columns[0]]

Unnamed: 0
Brown        0.477466
Columbia     0.505277
Cornell      0.463341
Dartmouth    0.507904
Harvard      0.506199
Princeton    0.503014
Penn         0.476095
Yale         0.491871
USA          0.492000
Name: Percent_Men, dtype: float64

In [ ]:
df.drop(columns=['Percent_Men', 'Percent_Women'], inplace=True)

Final Task: Calculate the percent of men, women, and each race for the undergraduate students at each university 

Optional: Calculate the percentages using a for loop

In [ ]:
df.columns[13]

'Percent_Women'

In [ ]:
for i in range(len(df.columns[:-1])):
  print(i)

0
1
2
3
4
5
6
7
8
9
10

In [ ]:
for x in range(len(df.columns[:-1])):
  df["Percent_" + df.columns[x]] = df[df.columns[x]]/df['Total'] 
  print(df["Percent_" + df.columns[x]])

Unnamed: 0
Brown        0.477466
Columbia     0.505277
Cornell      0.463341
Dartmouth    0.507904
Harvard      0.506199
Princeton    0.503014
Penn         0.476095
Yale         0.491871
USA          0.492000
Name: Percent_Men, dtype: float64
Unnamed: 0
Brown        0.522534
Columbia     0.494723
Cornell      0.541132
Dartmouth    0.492096
Harvard      0.493801
Princeton    0.496986
Penn         0.523905
Yale         0.508129
USA          0.508000
Name: Percent_Women, dtype: float64
Unnamed: 0
Brown        0.114428
Columbia     0.187090
Cornell      0.103699
Dartmouth    0.098053
Harvard      0.121583
Princeton    0.120196
Penn         0.134445
Yale         0.101987
USA               NaN
Name: Percent_Nonresident Aliens, dtype: float64
Unnamed: 0
Brown        0.111062
Columbia     0.133430
Cornell      0.138822
Dartmouth    0.105155
Harvard      0.109783
Princeton    0.104748
Penn         0.101208
Yale         0.141238
USA          0.185000
Name: Percent_Hispanic/Latino, dtype: float64
Unnamed: 0
Brown        0.067749
Columbia     0.065215
Cornell      0.066707
Dartmouth    0.058190
Harvard      0.089171
Princeton    0.078937
Penn         0.076854
Yale         0.076039
USA          0.134000
Name: Percent_Black or African American, non-Hispanic, dtype: float64
Unnamed: 0
Brown        0.427714
Columbia     0.356516
Cornell      0.357839
Dartmouth    0.505613
Harvard      0.371471
Princeton    0.402411
Penn         0.385268
Yale         0.404007
USA          0.601000
Name: Percent_White, non-Hispanic, dtype: float64
Unnamed: 0
Brown        0.003512
Columbia     0.004111
Cornell      0.003005
Dartmouth    0.013517
Harvard      0.002390
Princeton    0.001884
Penn         0.001098
Yale         0.004763
USA          0.013000
Name: Percent_American Indian or Alaska Native, non-Hispanic, dtype: float64
Unnamed: 0
Brown        0.166813
Columbia     0.167648
Cornell      0.198851
Dartmouth    0.147995
Harvard      0.214040
Princeton    0.223060
Penn         0.224973
Yale         0.200526
USA          0.059000
Name: Percent_Asian, non-Hispanic, dtype: float64
Unnamed: 0
Brown        0.001756
Columbia     0.001222
Cornell      0.001002
Dartmouth    0.001833
Harvard      0.000448
Princeton    0.001130
Penn         0.000499
Yale         0.000985
USA          0.002000
Name: Percent_Native Hawaiian or other Pacific Islander, non-Hispanic, dtype: float64
Unnamed: 0
Brown        0.060726
Columbia     0.052550
Cornell      0.049546
Dartmouth    0.055441
Harvard      0.077521
Princeton    0.052751
Penn         0.050704
Yale         0.065200
USA          0.028000
Name: Percent_Two or more races, non-Hispanic, dtype: float64
Unnamed: 0
Brown        0.046239
Columbia     0.032219
Cornell      0.080529
Dartmouth    0.014204
Harvard      0.013592
Princeton    0.013188
Penn         0.024953
Yale         0.005255
USA               NaN
Name: Percent_Race and/or ethnicity unknown, dtype: float64

In [ ]:
df.head()

               Men  ...  Percent_Race and/or ethnicity unknown
Unnamed: 0          ...
Brown       3263.0  ...                               0.046239
Columbia    4548.0  ...                               0.032219
Cornell     6939.0  ...                               0.080529
Dartmouth   2217.0  ...                               0.014204
Harvard     3389.0  ...                               0.013592

[5 rows x 23 columns]

Bonus: Dealing with null values

In [ ]:
df.tail()

                    Men        Women  ...  Percent_Men  Percent_Nonresident Aliens
Unnamed: 0                            ...
Harvard          3389.0       3306.0  ...     0.506199                    0.121583
Princeton        2670.0       2638.0  ...     0.503014                    0.120196
Penn             4770.0       5249.0  ...     0.476095                    0.134445
Yale             2995.0       3094.0  ...     0.491871                    0.101987
USA         161493845.3  166745677.7  ...     0.492000                         NaN

[5 rows x 14 columns]

In [ ]:
# Notice USA's Non-resident alients + Race and/or ethnicity unknown
df.loc['USA', :]

Men                                                                1.614938e+08
Women                                                              1.667457e+08
Nonresident Aliens                                                          NaN
Hispanic/Latino                                                    6.072431e+07
Black or African American, non-Hispanic                            4.398410e+07
White, non-Hispanic                                                1.972720e+08
American Indian or Alaska Native, non-Hispanic                     4.267114e+06
Asian, non-Hispanic                                                1.936613e+07
Native Hawaiian or other Pacific Islander, non-Hispanic            6.564790e+05
Two or more races, non-Hispanic                                    9.190707e+06
Race and/or ethnicity unknown                                               NaN
Total                                                              3.282395e+08
Percent_Men                                                        4.920000e-01
Percent_Women                                                      5.080000e-01
Percent_Nonresident Aliens                                                  NaN
Percent_Hispanic/Latino                                            1.850000e-01
Percent_Black or African American, non-Hispanic                    1.340000e-01
Percent_White, non-Hispanic                                        6.010000e-01
Percent_American Indian or Alaska Native, non-Hispanic             1.300000e-02
Percent_Asian, non-Hispanic                                        5.900000e-02
Percent_Native Hawaiian or other Pacific Islander, non-Hispanic    2.000000e-03
Percent_Two or more races, non-Hispanic                            2.800000e-02
Percent_Race and/or ethnicity unknown                                       NaN
Name: USA, dtype: float64

In [ ]:
df.isna()

              Men  ...  Percent_Race and/or ethnicity unknown
Unnamed: 0         ...
Brown       False  ...                                  False
Columbia    False  ...                                  False
Cornell     False  ...                                  False
Dartmouth   False  ...                                  False
Harvard     False  ...                                  False
Princeton   False  ...                                  False
Penn        False  ...                                  False
Yale        False  ...                                  False
USA         False  ...                                   True

[9 rows x 23 columns]

In [ ]:
print("Percentage of values missing: ", df.isna().mean().sum())
print("Total number of values missing: ", df.isna().sum().sum())

Percentage of values missing:  0.4444444444444444
Total number of values missing:  4

In [ ]:
df_new = pd.read_csv('/content/drive/Shared drives/Data Science for Social Good/Week_1/Day_7/porto-alegre-transportation.csv ')

SyntaxError: ignored

In [ ]:
df = pd.read_csv('/content/drive/Shared drives/Data Science for Social Good/Week_1/Day_7/porto-alegre-transportation.csv')

In [ ]:
df.head(df.index.size)

            mode travel_bounds      trips  distance_km     co2e_tons
0     AUTOMOBILE   IN-BOUNDARY  584896586   4982589664  1.093761e+06
1     AUTOMOBILE       INBOUND   82427160   3181612056  6.984164e+05
2     AUTOMOBILE      OUTBOUND   82892861   3116175344  6.840520e+05
3     AUTOMOBILE         TOTAL  750216607  11280377064  2.476229e+06
4        CYCLING   IN-BOUNDARY   14309184     44726087  0.000000e+00
5        CYCLING       INBOUND     554460      5548637  0.000000e+00
6        CYCLING      OUTBOUND     553422      5541330  0.000000e+00
7        CYCLING         TOTAL   15417066     55816054  0.000000e+00
8     MOTORCYCLE   IN-BOUNDARY   39125519    324997000  2.369683e+04
9     MOTORCYCLE       INBOUND   10791799    231094185  1.685000e+04
10    MOTORCYCLE      OUTBOUND   10360215    222409151  1.621674e+04
11    MOTORCYCLE         TOTAL   60277533    778500336  5.676357e+04
12  STANDARD BUS   IN-BOUNDARY   72917599    615553539  5.665904e+05
13  STANDARD BUS       INBOUND    6235979    236409838  2.176050e+05
14  STANDARD BUS      OUTBOUND    6681355    259123316  2.385118e+05
15  STANDARD BUS         TOTAL   85834933   1111086693  1.022707e+06
16        SUBWAY       INBOUND    6957379    155925441  0.000000e+00
17        SUBWAY      OUTBOUND    7147356    164402044  0.000000e+00
18        SUBWAY         TOTAL   14104735    320327485  0.000000e+00
19       WALKING   IN-BOUNDARY  386438906    266837128  0.000000e+00
20       WALKING       INBOUND    1796807      5896332  0.000000e+00
21       WALKING      OUTBOUND    1747936      5661356  0.000000e+00
22       WALKING         TOTAL  389983649    278394816  0.000000e+00

In [ ]:
df_inboundary = df[df['travel_bounds'] == "IN-BOUNDARY"]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

IndexingError: ignored

In [ ]:
df['mode'] == 'WALKING'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19     True
20     True
21     True
22     True
Name: mode, dtype: bool

In [ ]:
df_auto = df[df['mode'] == 'AUTOMOBILE']

In [ ]:
df_bus = df[df['mode'] == 'STANDARD BUS']

In [ ]:
df_auto

         mode travel_bounds      trips  distance_km     co2e_tons
0  AUTOMOBILE   IN-BOUNDARY  584896586   4982589664  1.093761e+06
1  AUTOMOBILE       INBOUND   82427160   3181612056  6.984164e+05
2  AUTOMOBILE      OUTBOUND   82892861   3116175344  6.840520e+05
3  AUTOMOBILE         TOTAL  750216607  11280377064  2.476229e+06

In [ ]:
df_bus

            mode travel_bounds     trips  distance_km     co2e_tons
12  STANDARD BUS   IN-BOUNDARY  72917599    615553539  5.665904e+05
13  STANDARD BUS       INBOUND   6235979    236409838  2.176050e+05
14  STANDARD BUS      OUTBOUND   6681355    259123316  2.385118e+05
15  STANDARD BUS         TOTAL  85834933   1111086693  1.022707e+06

In [ ]:
# iterate through to add
sum_auto = 0
for dist in df_auto['distance_km']:
  sum_auto += dist
print(sum_auto)

22560754128

In [ ]:
sum

In [ ]:
df_auto['distance_km']

0     4982589664
1     3181612056
2     3116175344
3    11280377064
Name: distance_km, dtype: int64

In [ ]:
import numpy as np
# quick function
np.sum(df_auto['distance_km'])

22560754128

In [ ]:
# get the distance km of auto
dist_auto = np.sum(df_auto['distance_km'])

# get distance in km of bus
dist_bus = np.sum(df_bus['distance_km'])

# compare
print(dist_auto > dist_bus)

True